set_property PACKAGE_PIN W5 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_i]
set_property PACKAGE_PIN T18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
# inp1
set_property PACKAGE_PIN V17 [get_ports inp1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports inp1[0]]
set_property PACKAGE_PIN V16 [get_ports inp1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports inp1[1]]
set_property PACKAGE_PIN W16 [get_ports inp1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports inp1[2]]
set_property PACKAGE_PIN W17 [get_ports inp1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports inp1[3]]

# inp2
set_property PACKAGE_PIN W15 [get_ports inp2[0]]
set_property IOSTANDARD LVCMOS33 [get_ports inp2[0]]
set_property PACKAGE_PIN V15 [get_ports inp2[1]]
set_property IOSTANDARD LVCMOS33 [get_ports inp2[1]]
set_property PACKAGE_PIN W14 [get_ports inp2[2]]
set_property IOSTANDARD LVCMOS33 [get_ports inp2[2]]
set_property PACKAGE_PIN W13 [get_ports inp2[3]]
set_property IOSTANDARD LVCMOS33 [get_ports inp2[3]]

# inp3
set_property PACKAGE_PIN V2 [get_ports inp3[0]]
set_property IOSTANDARD LVCMOS33 [get_ports inp3[0]]
set_property PACKAGE_PIN T3 [get_ports inp3[1]]
set_property IOSTANDARD LVCMOS33 [get_ports inp3[1]]
set_property PACKAGE_PIN T2 [get_ports inp3[2]]
set_property IOSTANDARD LVCMOS33 [get_ports inp3[2]]
set_property PACKAGE_PIN R3 [get_ports inp3[3]]
set_property IOSTANDARD LVCMOS33 [get_ports inp3[3]]

# inp4
set_property PACKAGE_PIN W2 [get_ports inp4[0]]
set_property IOSTANDARD LVCMOS33 [get_ports inp4[0]]
set_property PACKAGE_PIN U1 [get_ports inp4[1]]
set_property IOSTANDARD LVCMOS33 [get_ports inp4[1]]
set_property PACKAGE_PIN T1 [get_ports inp4[2]]
set_property IOSTANDARD LVCMOS33 [get_ports inp4[2]]
set_property PACKAGE_PIN R2 [get_ports inp4[3]]
set_property IOSTANDARD LVCMOS33 [get_ports inp4[3]]

## Anodes for 7-segment display
set_property PACKAGE_PIN U2 [get_ports ands[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ands[0]]
set_property PACKAGE_PIN U4 [get_ports ands[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ands[1]]
set_property PACKAGE_PIN V4 [get_ports ands[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ands[2]]
set_property PACKAGE_PIN W4 [get_ports ands[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ands[3]]

## 7-segment display cathodes
set_property PACKAGE_PIN W7 [get_ports cathodeout[0]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[0]]
set_property PACKAGE_PIN W6 [get_ports cathodeout[1]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[1]]
set_property PACKAGE_PIN U8 [get_ports cathodeout[2]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[2]]
set_property PACKAGE_PIN V8 [get_ports cathodeout[3]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[3]]
set_property PACKAGE_PIN U5 [get_ports cathodeout[4]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[4]]
set_property PACKAGE_PIN V5 [get_ports cathodeout[5]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[5]]
set_property PACKAGE_PIN U7 [get_ports cathodeout[6]]
set_property IOSTANDARD LVCMOS33 [get_ports cathodeout[6]]
